/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as counterSol from './Counter.sol/index.js';
export type { counterSol };
import type * as rewardSol from './Reward.sol/index.js';
export type { rewardSol };
export * as factories from './factories/index.js';
export type { Counter } from './Counter.sol/Counter.js';
export { Counter__factory } from './factories/Counter.sol/Counter__factory.js';
export type { Reward } from './Reward.sol/Reward.js';
export { Reward__factory } from './factories/Reward.sol/Reward__factory.js';